/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(h){function B(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function p(a){if(w)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!r(b)&&(b=b.parentNode););a.__importDoc=b}return b}function L(a){var b=l(document,
"link[rel=import]:not([import-dependency])"),c=b.length;c?g(b,function(b){return t(b,function(){0===--c&&a()})}):a()}function C(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function D(a){C(function(){return L(function(){return a&&a()})})}function t(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();
else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);x&&"style"===a.localName||a.addEventListener("error",c)}}function r(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.documents={};this.inflight=0;this.dynamicImportsMO=new MutationObserver(function(b){return a.handleMutations(b)});this.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function E(a){g(l(a,
"template"),function(a){g(l(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(a){var b=document.createElement("script");g(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});E(a.content)})}function l(a,b){return a.childNodes.length?a.querySelectorAll(b):M}function g(a,b,c){var d=a?a.length:0,f=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=f)b(a[c],c)}var m=
document.createElement("link"),w="import"in m,M=m.querySelectorAll("*"),y=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return y||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var N=/(url\()([^)]*)(\))/g,O=/(@import[\s]+(?!url\())([^;]*)(;)/g,P=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,e={fixUrls:function(a,b){a.href&&a.setAttribute("href",e.resolveUrl(a.getAttribute("href"),b));
a.src&&a.setAttribute("src",e.resolveUrl(a.getAttribute("src"),b));if("style"===a.localName){var c=e.replaceUrls(a.textContent,b,N);a.textContent=e.replaceUrls(c,b,O)}},replaceUrls:function(a,b,c){return a.replace(c,function(a,c,n,g){a=n.replace(/["']/g,"");b&&(a=e.resolveUrl(a,b));return c+"'"+a+"'"+g})},resolveUrl:function(a,b){if(void 0===e.__workingURL){e.__workingURL=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";e.__workingURL="http://a/c%20d"===c.href}catch(d){}}if(e.__workingURL)return(new URL(a,
b)).href;c=e.__tempDoc;c||(c=document.implementation.createHTMLDocument("temp"),e.__tempDoc=c,c.__base=c.createElement("base"),c.head.appendChild(c.__base),c.__anchor=c.createElement("a"));c.__base.href=b;c.__anchor.href=a;return c.__anchor.href||a}},F={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var f=new XMLHttpRequest;f.open("GET",a,F.async);f.onload=function(){var a=f.responseURL||f.getResponseHeader("Location");
a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=f.response||f.responseText;304===f.status||0===f.status||200<=f.status&&300>f.status?b(d,a):c(d)};f.send()}else c("error: href must be specified")}},x=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);k.prototype.loadImports=function(a){var b=this;a=l(a,"link[rel=import]");g(a,function(a){return b.loadImport(a)})};k.prototype.loadImport=function(a){var b=this,c=a.href;if(void 0!==this.documents[c]){var d=
this.documents[c];d&&d.__loaded&&(a.__import=d,this.fireEventIfNeeded(a))}else this.inflight++,this.documents[c]="pending",F.load(c,function(a,d){a=b.makeDocument(a,d||c);b.documents[c]=a;b.inflight--;b.loadImports(a);b.processImportsIfLoadingDone()},function(){b.documents[c]=null;b.inflight--;b.processImportsIfLoadingDone()})};k.prototype.makeDocument=function(a,b){if(!a)return document.createDocumentFragment();x&&(a=a.replace(P,function(a,b,c){return-1===a.indexOf("type=")?b+" type=import-disable "+
c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,E(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=e.resolveUrl(c.getAttribute("href"),b),c.removeAttribute("href");c=l(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');
var d=0;g(c,function(a){t(a);e.fixUrls(a,b);a.setAttribute("import-dependency","");if("script"===a.localName&&!a.src&&a.textContent){if("module"===a.type)throw Error("Inline module scripts are not supported in HTML Imports.");a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n")));a.textContent="";d++}});return a};k.prototype.processImportsIfLoadingDone=function(){var a=this;if(!this.inflight){this.dynamicImportsMO.disconnect();
this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.inflight||(a.dynamicImportsMO.observe(document.head,{childList:!0,subtree:!0}),a.fireEvents()))};this.waitForStyles(function(){c=!0;d()});this.runScripts(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=l(a,"link[rel=import]");g(a,function(a){var c=b.documents[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.documents[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),
a.appendChild(c))})};k.prototype.runScripts=function(a){function b(f){if(f<d){var n=c[f],e=document.createElement("script");n.removeAttribute("import-dependency");g(n.attributes,function(a){return e.setAttribute(a.name,a.value)});y=e;n.parentNode.replaceChild(e,n);t(e,function(){y=null;b(f+1)})}else a()}var c=l(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.waitForStyles=function(a){var b=l(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),c=b.length;
if(c){var d=x&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");g(b,function(b){t(b,function(){b.removeAttribute("import-dependency");0===--c&&a()});if(d&&b.parentNode!==document.head){var e=document.createElement(b.localName);e.__appliedElement=b;e.setAttribute("type","import-placeholder");b.parentNode.insertBefore(e,b.nextSibling);for(e=p(b);e&&p(e);)e=p(e);e.parentNode!==document.head&&(e=null);document.head.insertBefore(b,e);b.removeAttribute("type")}})}else a()};k.prototype.fireEvents=
function(){var a=this,b=l(document,"link[rel=import]");g(b,function(b){return a.fireEventIfNeeded(b)},!0)};k.prototype.fireEventIfNeeded=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(B(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.handleMutations=function(a){var b=this;g(a,function(a){return g(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(r(a)?b.loadImport(a):b.loadImports(a))})})};var z=null;if(w)m=
l(document,"link[rel=import]"),g(m,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),m=function(a){a=a.target;r(a)&&(a.__loaded=!0)},document.addEventListener("load",m,!0),document.addEventListener("error",m,!0);else{var q=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!q||q.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=r(this)?this:p(this);return a?a.href:q&&q.get?q.get.call(this):(document.querySelector("base")||window.location).href},
configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});C(function(){z=new k})}D(function(){return document.dispatchEvent(B("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});h.useNative=w;h.whenReady=D;h.importForElement=p;h.loadImports=function(a){z&&z.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var u=window.customElements,v=window.HTMLImports,A=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(u&&u.polyfillWrapFlushCallback){var G,H=function(){if(G){A.bootstrap&&A.bootstrap(window.document);var h=G;G=null;h();return!0}},I=v.whenReady;u.polyfillWrapFlushCallback(function(h){G=h;I(H)});v.whenReady=function(h){I(function(){H()?v.whenReady(h):h()})}}
v.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var J=document.createElement("style");J.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var K=document.querySelector("head");K.insertBefore(J,K.firstChild);/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);
